### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by wichert** [marcelcaraciolo/crab#18]
Are you interested in a pull request which makes the codebase PEP8 complient?

**Comment by marcelcaraciolo** [comment]
Hi wichert, of course any contributions are welcome! We will release also our user guide with examples and the docummentation until the end of this month :D

Regards,
Marcel

**Comment by marcelcaraciolo** [comment]
HI wichert , this project now is being migrated to the github.com/muricoca/crab

**Comment by wichert** [comment]
I've submitted a pull request in ticket #19, which obsoletes this issue.
